language: scala
scala:
- 2.11.8
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.ivy2/cache"
before_cache:
- rm -rf $HOME/.ivy2/cache/com.typesafe.play/*
- rm -rf $HOME/.ivy2/cache/scala_*/sbt_*/com.typesafe.play/*
- find $HOME/.ivy2/cache -name "ivydata-*.properties" -print0 | xargs -n10 -0 rm
notifications:
  slack:
    secure: a738ADtNq3eN26B6LCcd+NY83s+PQjQagL0S9HhBFvCpvzkQ/CwAK9l5keWayM2S4IUBOmsS/uMuKodmP7QoPN3XxUGgsZNTMjHT1FAa/rc6N2MKF5C20fBII1/cJOuXBZ5x+2EW+odch3+0pafMCXI/RZZLiHELD2Jx6JGS0lQ=
